### ISSUE TITLE
Test Creating new tag

### ISSUE THREAD

**Issue by Gabkings** [LondonAppDeveloper/recipe-app-api#1]
The test for creating a new tag is failing man, I don't know how you fixed your's to pass in your video.

**Comment by LondonAppDev** [comment]
**Please submit any course-related questions to the Udemy Q&A**

This is so we have one central location where all of the knowledge about the course is located (questions asked and answered by students and instructors). This helps us address students’ questions faster and more efficiently - plus it helps students learn from each other.

**Comment by LondonAppDev** [comment]
**Please submit any course-related questions to the Udemy Q&A**

This is so we have one central location where all of the knowledge about the course is located (questions asked and answered by students and instructors). This helps us address students’ questions faster and more efficiently - plus it helps students learn from each other.
